# Generated by Django 5.2.11 on 2026-02-06 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_item_location_item_rating_item_reviews_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_name", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                            ("AwaitingPayment", "AwaitingPayment"),
                            ("ReceiptConfirmed", "ReceiptConfirmed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("rating_given", models.IntegerField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="core.item",
                    ),
                ),
            ],
        ),
    ]
