# Generated by Django 5.2.11 on 2026-02-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_notification_rentalrequest_owner_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="delivery_method",
            field=models.CharField(default="Both", max_length=50),
        ),
        migrations.AddField(
            model_name="item",
            name="owner_id",
            field=models.CharField(default="user123", max_length=100),
        ),
    ]
