# Generated by Django 5.2.11 on 2026-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_item_delivery_method_item_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="owner_id",
            field=models.CharField(db_index=True, default="user123", max_length=100),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_user_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="rentalrequest",
            name="owner_id",
            field=models.CharField(db_index=True, default="user456", max_length=100),
        ),
        migrations.AlterField(
            model_name="rentalrequest",
            name="requester_id",
            field=models.CharField(db_index=True, default="user123", max_length=100),
        ),
    ]
